spring:
  application:
    name: generic-crud-testing
  datasource:
    url: jdbc:postgresql://localhost:5432/generic_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect